frontend/src/Entity/Service.php
<?php

declare(strict_types = 1);

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ServiceRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Service
{
    use HistoryTrackableEntity;

    public const SERVICE_STATUS_NORMAL = 0;

    public const SERVICE_STATUS_ALTERED = 10;

    public const SERVICE_STATUS_OVERLOADED = 20;

    public const SERVICE_STATUS_PARTIAL_ACTIVITY = 30;

    public const SERVICE_STATUS_SCARCE = 40;

    public const SERVICE_STATUS_STOPPED = 50;

    public const SERVICE_LABEL_NORMAL = 'service.activity.normal';

    public const SERVICE_LABEL_ALTERED = 'service.activity.altered';

    public const SERVICE_LABEL_OVERLOADED = 'service.activity.overloaded';

    public const SERVICE_LABEL_PARTIAL_ACTIVITY = 'service.activity.partial';

    public const SERVICE_LABEL_SCARCE = 'service.activity.scarce';

    public const SERVICE_LABEL_STOPPED = 'service.activity.stopped';

    public const SERVICE_TYPE_PUBLIC_INSTITUTION = 0;

    public const SERVICE_TYPE_STORE = 10;

    public const SERVICE_TYPE_PRIVATE_SERVICE = 20;

    public const SERVICE_LABEL_PUBLIC_INSTITUTION = 'service.type.public.institution';

    public const SERVICE_LABEL_STORE = 'service.type.store';

    public const SERVICE_LABEL_PRIVATE_SERVICE = 'service.type.private.service';

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="smallint")
     */
    private $status;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $source;

    /**
     * @ORM\Column(type="text")
     */
    private $information;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $source2;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="integer")
     */
    private $type;

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return int|null
     */
    public function getStatus(): ?int
    {
        return $this->status;
    }

    /**
     * @param int $status
     *
     * @return $this
     */
    public function setStatus(int $status): self
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getName(): ?string
    {
        return (string)$this->name;
    }

    /**
     * @param string $name
     *
     * @return $this
     */
    public function setName(?string $name): self
    {
        $this->name = (string)$name;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getSource(): ?string
    {
        return $this->source;
    }

    /**
     * @param string $source
     *
     * @return $this
     */
    public function setSource(?string $source): self
    {
        $this->source = (string)$source;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getInformation(): ?string
    {
        return (string)$this->information;
    }

    /**
     * @param string $information
     *
     * @return $this
     */
    public function setInformation(?string $information): self
    {
        $this->information = (string)$information;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getPhone(): ?string
    {
        return (string)$this->phone;
    }

    /**
     * @param string $phone
     *
     * @return $this
     */
    public function setPhone(?string $phone): self
    {
        $this->phone = (string)$phone;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getEmail(): ?string
    {
        return (string)$this->email;
    }

    /**
     * @param string $email
     *
     * @return $this
     */
    public function setEmail(?string $email): self
    {
        $this->email = (string)$email;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getSource2(): ?string
    {
        return (string)$this->source2;
    }

    /**
     * @param string $source2
     *
     * @return $this
     */
    public function setSource2(?string $source2): self
    {
        $this->source2 = (string)$source2;

        return $this;
    }

    /**
     * @return array
     */
    public static function getActivityStatus(): array
    {
        return [
            static::SERVICE_STATUS_NORMAL           => static::SERVICE_LABEL_NORMAL,
            static::SERVICE_STATUS_ALTERED          => static::SERVICE_LABEL_ALTERED,
            static::SERVICE_STATUS_OVERLOADED       => static::SERVICE_LABEL_OVERLOADED,
            static::SERVICE_STATUS_PARTIAL_ACTIVITY => static::SERVICE_LABEL_PARTIAL_ACTIVITY,
            static::SERVICE_STATUS_SCARCE           => static::SERVICE_LABEL_SCARCE,
            static::SERVICE_STATUS_STOPPED          => static::SERVICE_LABEL_STOPPED,
        ];
    }

    /**
     * @return array
     */
    public static function getActivityChoices(): array
    {
        return \array_flip(static::getActivityStatus());
    }

    /**
     * @return array
     */
    public static function getTypes(): array
    {
        return [
            static::SERVICE_TYPE_PUBLIC_INSTITUTION => static::SERVICE_LABEL_PUBLIC_INSTITUTION,
            static::SERVICE_TYPE_STORE              => static::SERVICE_LABEL_STORE,
            static::SERVICE_TYPE_PRIVATE_SERVICE    => static::SERVICE_LABEL_PRIVATE_SERVICE,
        ];
    }

    /**
     * @return array
     */
    public static function getTypesChoices(): array
    {
        return \array_flip(static::getTypes());
    }

    /**
     * @return string|null
     */
    public function getAddress(): ?string
    {
        return (string)$this->address;
    }

    /**
     * @param string $address
     *
     * @return $this
     */
    public function setAddress(?string $address): self
    {
        $this->address = (string)$address;

        return $this;
    }

    /**
     * @return mixed|string
     */
    public function getStatusAsString()
    {
        return static::getActivityStatus()[$this->getStatus()] ?? static::SERVICE_LABEL_NORMAL;
    }

    /**
     * @return int|null
     */
    public function getType(): ?int
    {
        return $this->type;
    }

    /**
     * @param int $type
     *
     * @return $this
     */
    public function setType(int $type): self
    {
        $this->type = $type;

        return $this;
    }

    /**
     * @return mixed|string
     */
    public function getTypeAsString()
    {
        return static::getTypes()[(int)$this->getType()] ?? static::SERVICE_LABEL_PUBLIC_INSTITUTION;
    }
}

frontend/src/Form/ServiceType.php
<?php

declare(strict_types = 1);

namespace App\Form;

use App\Entity\Service;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class ServiceType.
 */
class ServiceType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('status', ChoiceType::class, ['choices' => Service::getActivityChoices()])
            ->add('type', ChoiceType::class, ['choices' => Service::getTypesChoices()])
            ->add('name')
            ->add('source')
            ->add('information', CKEditorType::class, ['config_name' => 'cityconfinement_ckeditor', 'required' => false])
            ->add('phone', null, ['required' => false])
            ->add('email', EmailType::class, ['required' => false])
            ->add('source2', null, ['required' => false])
            ->add('address', null, ['required' => false]);
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Service::class,
        ]);
    }
}

frontend/src/Controller/ServiceController.php
<?php

declare(strict_types = 1);

namespace App\Controller;

use App\Entity\Service;
use App\Form\ServiceType;
use App\Repository\ServiceRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/{_locale}/admin/service")
 *
 * @IsGranted("ROLE_ADMIN")
 */
class ServiceController extends AbstractController
{
    /**
     * @Route("/", name="service_index", methods={"GET"})
     *
     * @param ServiceRepository $serviceRepository
     *
     * @return Response
     */
    public function index(ServiceRepository $serviceRepository): Response
    {
        return $this->render(
            'service/index.html.twig',
            [
                'services' => $serviceRepository->findBy([], ['updated' => 'DESC']),
            ]
        );
    }

    /**
     * @Route("/new", name="service_new", methods={"GET", "POST"})
     *
     * @param Request $request
     *
     * @return Response
     */
    public function new(Request $request): Response
    {
        $service = new Service();
        $form = $this->createForm(ServiceType::class, $service);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($service);
            $entityManager->flush();

            return $this->redirectToRoute('service_index');
        }

        return $this->render(
            'service/new.html.twig',
            [
                'service' => $service,
                'form'    => $form->createView(),
            ]
        );
    }

    /**
     * @Route("/{id}", name="service_show", methods={"GET"})
     *
     * @param Service $service
     *
     * @return Response
     */
    public function show(Service $service): Response
    {
        return $this->render(
            'service/show.html.twig',
            [
                'service' => $service,
            ]
        );
    }

    /**
     * @Route("/{id}/edit", name="service_edit", methods={"GET", "POST"})
     *
     * @param Request $request
     * @param Service $service
     *
     * @return Response
     */
    public function edit(Request $request, Service $service): Response
    {
        $form = $this->createForm(ServiceType::class, $service);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('service_index');
        }

        return $this->render(
            'service/edit.html.twig',
            [
                'service' => $service,
                'form'    => $form->createView(),
            ]
        );
    }

    /**
     * @Route("/{id}",
     *     name="service_delete",
     *     methods={"DELETE"},
     *     requirements={"id" = "\d+"}),
     * )
     *
     * @param Request $request
     * @param Service $service
     *
     * @return Response
     */
    public function delete(Request $request, Service $service): Response
    {
        if ($this->isCsrfTokenValid('delete' . $service->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($service);
            $entityManager->flush();
        }

        return $this->redirectToRoute('service_index');
    }
}

frontend/templates/service/_delete_form.html.twig
<form method="post" action="{{ path('service_delete', {'id': service.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ service.id) }}">
    <button class="btn">Delete</button>
</form>

frontend/templates/service/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

frontend/templates/service/edit.html.twig
{% extends 'admin_layout.html.twig' %}

{% block title %}Edit Service{% endblock %}

{% block body %}
    <div class="bg-white rounded-sm shadow-lg p-4 m-4">
        <a href="{{ path('service_index') }}" class="button" title="{{ 'back to list'|trans }}"
           aria-label="{{ 'back to list'|trans }}">{{ 'back to list'|trans }}</a>

        <h1>Edit Service</h1>

        {{ include('service/_form.html.twig', {'button_label': 'Update'}) }}

        {{ include('service/_delete_form.html.twig') }}
    </div>
{% endblock %}

frontend/templates/service/index.html.twig
{% extends 'admin_layout.html.twig' %}

{% block title %}Service index{% endblock %}

{% block body %}
    <div class="bg-white rounded-sm shadow-lg p-4 m-4 text-center">
        <h1>Service index</h1>

        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Status</th>
                    <th>Type</th>
                    <th>Source</th>
                    <th>Information</th>
                    <th>Phone</th>
                    <th>Email</th>
                    <th>Source2</th>
                    <th>Created</th>
                    <th>Updated</th>
                    <th>actions</th>
                </tr>
            </thead>
            <tbody>
                {% for service in services %}
                    <tr>
                        <td>{{ service.id }}</td>
                        <td><strong>{{ service.name }}</strong></td>
                        <td>{{ service.statusAsString|trans }}</td>
                        <td>{{ service.typeAsString|trans }}</td>
                        <td>{{ service.source|slice(0,50) }}</td>
                        <td>{{ service.information|slice(0,50) }}</td>
                        <td>{{ service.phone }}</td>
                        <td>{{ service.email }}</td>
                        <td>{{ service.source2|slice(0,50) }}</td>
                        <td>{{ service.created ? service.created|date('Y-m-d H:i:s') : '' }}</td>
                        <td>{{ service.created ? service.updated|date('Y-m-d H:i:s') : '' }}</td>
                        <td class="actions">
                            <a href="{{ path('service_show', {'id': service.id}) }}">show</a>
                            <a href="{{ path('service_edit', {'id': service.id}) }}">edit</a>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="9">{{ 'No records found'|trans }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        <a href="{{ path('service_new') }}" class="button" title="{{ 'Create new'|trans }}"
           aria-label="{{ 'Create new'|trans }}">{{ 'Create new'|trans }}
        </a>
    </div>
{% endblock %}

frontend/templates/service/new.html.twig
{% extends 'admin_layout.html.twig' %}

{% block title %}New Service{% endblock %}

{% block body %}
    <div class="bg-white rounded-sm shadow-lg p-4 m-4">

        <a href="{{ path('service_index') }}" class="button" title="{{ 'back to list'|trans }}"
           aria-label="{{ 'back to list'|trans }}">{{ 'back to list'|trans }}</a>

        <h1>{{ 'Create new'|trans }} Service</h1>

        {{ include('service/_form.html.twig') }}
    </div>
{% endblock %}

frontend/templates/service/show.html.twig
{% extends 'admin_layout.html.twig' %}

{% block title %}Service{% endblock %}

{% block body %}
    <div class="bg-white rounded-sm shadow-lg p-4 m-4">

        <a href="{{ path('service_index') }}" class="button" title="{{ 'back to list'|trans }}"
           aria-label="{{ 'back to list'|trans }}">{{ 'back to list'|trans }}</a>

        <h1>Service</h1>

        <table class="table">
            <tbody>
                <tr>
                    <th>Id</th>
                    <td>{{ service.id }}</td>
                </tr>
                <tr>
                    <th>Status</th>
                    <td>{{ service.status }}</td>
                </tr>
                <tr>
                    <th>Name</th>
                    <td>{{ service.name }}</td>
                </tr>
                <tr>
                    <th>Source</th>
                    <td>{{ service.source }}</td>
                </tr>
                <tr>
                    <th>Information</th>
                    <td>{{ service.information }}</td>
                </tr>
                <tr>
                    <th>Phone</th>
                    <td>{{ service.phone }}</td>
                </tr>
                <tr>
                    <th>Email</th>
                    <td>{{ service.email }}</td>
                </tr>
                <tr>
                    <th>Source2</th>
                    <td>{{ service.source2 }}</td>
                </tr>
            </tbody>
        </table>

        <a href="{{ path('service_edit', {'id': service.id}) }}" class="button">edit</a>

        {{ include('service/_delete_form.html.twig') }}
    </div>
{% endblock %}