frontend/src/Entity/Source.php
<?php

declare(strict_types = 1);

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SourceRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Source
{
    use HistoryTrackableEntity;

    public const SOURCE_TYPE_KEY_AUTHORITIES = 0;

    public const SOURCE_TYPE_KEY_OFFICIAL = 10;

    public const SOURCE_TYPE_KEY_FUN = 20;

    public const SOURCE_TYPE_KEY_FAKE = 30;

    public const SOURCE_TYPE_LABEL_AUTHORITIES = 'Authorities';

    public const SOURCE_TYPE_LABEL_OFFICIAL = 'Official';

    public const SOURCE_TYPE_LABEL_FUN = 'Fun';

    public const SOURCE_TYPE_LABEL_FAKE = 'Fake';

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $url;

    /**
     * @ORM\Column(type="integer")
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255, options={"default" = ""})
     */
    private $facebook_url;

    /**
     * @ORM\Column(type="string", length=255, options={"default" = ""})
     */
    private $twitter_url;

    /**
     * @ORM\Column(type="string", length=255, options={"default" = ""})
     */
    private $instagram_url;

    /**
     * @ORM\Column(type="string", length=255, options={"default" = ""})
     */
    private $description;

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string|null
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * @param string $name
     *
     * @return $this
     */
    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getUrl(): ?string
    {
        return (string)$this->url;
    }

    /**
     * @param string $url
     *
     * @return $this
     */
    public function setUrl(?string $url): self
    {
        $this->url = (string)$url;

        return $this;
    }

    /**
     * @return int|null
     */
    public function getType(): ?int
    {
        return $this->type;
    }

    /**
     * @param int $type
     *
     * @return $this
     */
    public function setType(int $type): self
    {
        $this->type = $type;

        return $this;
    }

    /**
     * @return string
     */
    public function getFacebookUrl(): string
    {
        return (string)$this->facebook_url;
    }

    /**
     * @param string|null $facebook_url
     *
     * @return $this
     */
    public function setFacebookUrl(?string $facebook_url): self
    {
        $this->facebook_url = (string)$facebook_url;

        return $this;
    }

    /**
     * @return string
     */
    public function getTwitterUrl(): string
    {
        return (string)$this->twitter_url;
    }

    /**
     * @param string|null $twitter_url
     *
     * @return $this
     */
    public function setTwitterUrl(?string $twitter_url): self
    {
        $this->twitter_url = (string)$twitter_url;

        return $this;
    }

    /**
     * @return string
     */
    public function getInstagramUrl(): string
    {
        return (string)$this->instagram_url;
    }

    /**
     * @param string|null $instagram_url
     *
     * @return $this
     */
    public function setInstagramUrl(?string $instagram_url): self
    {
        $this->instagram_url = (string)$instagram_url;

        return $this;
    }

    /**
     * @return string
     */
    public function getDescription(): string
    {
        return (string)$this->description;
    }

    /**
     * @param string|null $description
     *
     * @return $this
     */
    public function setDescription(?string $description): self
    {
        $this->description = (string)$description;

        return $this;
    }

    /**
     * @return array
     */
    public static function getTypesArray(): array
    {
        return [
            static::SOURCE_TYPE_KEY_AUTHORITIES => static::SOURCE_TYPE_LABEL_AUTHORITIES,
            static::SOURCE_TYPE_KEY_OFFICIAL    => static::SOURCE_TYPE_LABEL_OFFICIAL,
            static::SOURCE_TYPE_KEY_FUN         => static::SOURCE_TYPE_LABEL_FUN,
            static::SOURCE_TYPE_KEY_FAKE        => static::SOURCE_TYPE_LABEL_FAKE,
        ];
    }

    /**
     * @param int $typeKey
     *
     * @return string
     */
    public static function typeKeyToString(int $typeKey): string
    {
        return self::getTypesArray()[$typeKey] ?? '';
    }

    /**
     * @return mixed|string
     */
    public function getTypeAsString()
    {
        return self::getTypesArray()[$this->getType()] ?? '';
    }
}

frontend/src/Form/SourceType.php
<?php

declare(strict_types = 1);

namespace App\Form;

use App\Entity\Source;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class SourceType.
 */
class SourceType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('type',
                ChoiceType::class,
                [
                    'choices'                   => [
                        Source::SOURCE_TYPE_LABEL_AUTHORITIES => Source::SOURCE_TYPE_KEY_AUTHORITIES,
                        Source::SOURCE_TYPE_LABEL_OFFICIAL    => Source::SOURCE_TYPE_KEY_OFFICIAL,
                        Source::SOURCE_TYPE_LABEL_FUN         => Source::SOURCE_TYPE_KEY_FUN,
                        Source::SOURCE_TYPE_LABEL_FAKE        => Source::SOURCE_TYPE_KEY_FAKE,
                    ],
                    'choice_translation_domain' => true,
                ]
            )
            ->add('description', null, ['required' => false])
            ->add('url', null, ['required' => false])
            ->add('facebook_url', null, ['required' => false])
            ->add('twitter_url', null, ['required' => false])
            ->add('instagram_url', null, ['required' => false]);
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults(
            [
                'data_class' => Source::class,
            ]
        );
    }
}

frontend/src/Controller/SourceController.php
<?php

declare(strict_types = 1);

namespace App\Controller;

use App\Entity\Source;
use App\Form\SourceType;
use App\Repository\SourceRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/{_locale}/admin/source")
 *
 * @IsGranted("ROLE_ADMIN")
 */
class SourceController extends AbstractController
{
    /**
     * @Route("/", name="source_index", methods={"GET"})
     *
     * @param SourceRepository $sourceRepository
     *
     * @return Response
     */
    public function index(SourceRepository $sourceRepository): Response
    {
        return $this->render('source/index.html.twig', [
            'sources' => $sourceRepository->findBy([], ['updated' => 'DESC']),
        ]);
    }

    /**
     * @Route("/new", name="source_new", methods={"GET", "POST"})
     *
     * @param Request $request
     *
     * @return Response
     */
    public function new(Request $request): Response
    {
        $source = new Source();
        $form = $this->createForm(SourceType::class, $source);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($source);
            $entityManager->flush();

            return $this->redirectToRoute('source_index');
        }

        return $this->render('source/new.html.twig', [
            'source' => $source,
            'form'   => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="source_show", methods={"GET"})
     *
     * @param Source $source
     *
     * @return Response
     */
    public function show(Source $source): Response
    {
        return $this->render('source/show.html.twig', [
            'source' => $source,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="source_edit", methods={"GET", "POST"})
     *
     * @param Request $request
     * @param Source $source
     *
     * @return Response
     */
    public function edit(Request $request, Source $source): Response
    {
        $form = $this->createForm(SourceType::class, $source);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('source_index');
        }

        return $this->render(
            'source/edit.html.twig',
            [
                'source' => $source,
                'form'   => $form->createView(),
            ]
        );
    }

    /**
     * @Route("/{id}",
     *     name="source_delete",
     *     methods={"DELETE"},
     *     requirements={"id" = "\d+"}),
     * )
     *
     * @param Request $request
     * @param Source $source
     *
     * @return Response
     */
    public function delete(Request $request, Source $source): Response
    {
        if ($this->isCsrfTokenValid('delete' . $source->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($source);
            $entityManager->flush();
        }

        return $this->redirectToRoute('source_index');
    }
}

frontend/templates/source/_delete_form.html.twig
<form method="post" action="{{ path('source_delete', {'id': source.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ source.id) }}">
    <button class="btn">Delete</button>
</form>

frontend/templates/source/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

frontend/templates/source/edit.html.twig
{% extends 'admin_layout.html.twig' %}

{% block title %}Edit Source{% endblock %}

{% block body %}
    <div class="bg-white rounded-sm shadow-lg p-4 m-4">

        <a href="{{ path('source_index') }}" class="button" title="{{ 'back to list'|trans }}"
           aria-label="{{ 'back to list'|trans }}">{{ 'back to list'|trans }}</a>

        <h1>Edit Source</h1>

        {{ include('source/_form.html.twig', {'button_label': 'Update'}) }}

        {{ include('source/_delete_form.html.twig') }}
    </div>
{% endblock %}

frontend/templates/source/index.html.twig
{% extends 'admin_layout.html.twig' %}

{% block title %}Source index{% endblock %}

{% block body %}
    <div class="bg-white rounded-sm shadow-lg p-4 m-4 text-center">

        <h1>Source index</h1>

        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Type</th>
                    <th>Url</th>
                    <th>Facebook URL</th>
                    <th>Twitter URL</th>
                    <th>Instagram URL</th>
                    <th>Created</th>
                    <th>Update</th>
                    <th>Description</th>
                    <th>actions</th>
                </tr>
            </thead>
            <tbody>
                {% for source in sources %}
                    <tr>
                        <td>{{ source.id }}</td>
                        <td><strong>{{ source.name }}</strong></td>
                        <td>{{ source.typeAsString|trans }}</td>
                        <td>{{ source.url }}</td>
                        <td>{{ source.facebookUrl }}</td>
                        <td>{{ source.twitterUrl }}</td>
                        <td>{{ source.instagramUrl }}</td>
                        <td>{{ source.created ? source.created|date('Y-m-d') : '' }}</td>
                        <td>{{ source.updated ? source.updated|date('Y-m-d') : '' }}</td>
                        <td>{{ source.description|slice(0,50) }}</td>
                        <td class="actions">
                            <a href="{{ path('source_show', {'id': source.id}) }}">show</a>
                            <a href="{{ path('source_edit', {'id': source.id}) }}">edit</a>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="5">{{ 'No records found'|trans }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        <a href="{{ path('source_new') }}" class="button">{{ 'Create new'|trans }}</a>
    </div>
{% endblock %}

frontend/templates/source/new.html.twig
{% extends 'admin_layout.html.twig' %}

{% block title %}New Source{% endblock %}

{% block body %}
    <div class="bg-white rounded-sm shadow-lg p-4 m-4">

        <a href="{{ path('source_index') }}" class="button" title="{{ 'back to list'|trans }}"
           aria-label="{{ 'back to list'|trans }}">{{ 'back to list'|trans }}</a>

        <h1>{{ 'Create new'|trans }} Source</h1>

        {{ include('source/_form.html.twig') }}
    </div>
{% endblock %}

frontend/templates/source/show.html.twig
{% extends 'admin_layout.html.twig' %}

{% block title %}Source{% endblock %}

{% block body %}
    <div class="bg-white rounded-sm shadow-lg p-4 m-4">

        <a href="{{ path('source_index') }}" class="button" title="{{ 'back to list'|trans }}"
           aria-label="{{ 'back to list'|trans }}">{{ 'back to list'|trans }}</a>

        <h1>Source</h1>

        <table class="table">
            <tbody>
                <tr>
                    <th>Id</th>
                    <td>{{ source.id }}</td>
                </tr>
                <tr>
                    <th>Name</th>
                    <td>{{ source.name }}</td>
                </tr>
                <tr>
                    <th>Type</th>
                    <td>{{ source.type }}</td>
                </tr>
                <tr>
                    <th>Url</th>
                    <td>{{ source.url }}</td>
                </tr>
                <tr>
                    <th>Facebook URL</th>
                    <td>{{ source.facebook_url }}</td>
                </tr>
                <tr>
                    <th>Twitter URL</th>
                    <td>{{ source.twitter_url }}</td>
                </tr>
                <tr>
                    <th>Instagram URL</th>
                    <td>{{ source.instagram_url }}</td>
                </tr>
            </tbody>
        </table>

        <a href="{{ path('source_edit', {'id': source.id}) }}">edit</a>

        {{ include('source/_delete_form.html.twig') }}
    </div>
{% endblock %}